# Generated by Django 4.2.1 on 2023-05-09 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DBInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('projects', models.ManyToManyField(to='learn.project')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='users',
            field=models.ManyToManyField(to='learn.user'),
        ),
        migrations.CreateModel(
            name='DBInstanceNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('db_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learn.dbinstance')),
            ],
        ),
        migrations.CreateModel(
            name='DBInstanceBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('db_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learn.dbinstance')),
            ],
        ),
        migrations.AddField(
            model_name='dbinstance',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learn.project'),
        ),
    ]
